import { Product, Category, Banner, ShopeeReview } from "@/types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Kính cường lực",
    slug: "kinh-cuong-luc",
    icon: "🔲",
    productCount: 45,
  },
  {
    id: "2",
    name: "Ốp lưng",
    slug: "op-lung",
    icon: "📱",
    productCount: 120,
  },
  {
    id: "3",
    name: "Sạc & Adapter",
    slug: "sac-adapter",
    icon: "🔌",
    productCount: 35,
  },
  {
    id: "4",
    name: "Cáp sạc",
    slug: "cap-sac",
    icon: "🔗",
    productCount: 50,
  },
  {
    id: "5",
    name: "Tai nghe",
    slug: "tai-nghe",
    icon: "🎧",
    productCount: 28,
  },
  {
    id: "6",
    name: "Pin dự phòng",
    slug: "pin-du-phong",
    icon: "🔋",
    productCount: 15,
  },
  {
    id: "7",
    name: "Giá đỡ điện thoại",
    slug: "gia-do-dien-thoai",
    icon: "📲",
    productCount: 22,
  },
  {
    id: "8",
    name: "Phụ kiện khác",
    slug: "phu-kien-khac",
    icon: "📦",
    productCount: 40,
  },
];

const shopeeReviews: ShopeeReview[] = [
  {
    id: "r1",
    userName: "Nguyễn Văn A",
    rating: 5,
    comment:
      "Sản phẩm rất tốt, đóng gói cẩn thận. Kính dán rất khít, không bọt khí. Sẽ ủng hộ shop dài dài!",
    createdAt: "2024-12-15T10:00:00Z",
    likes: 12,
    variant: "iPhone 15 Pro Max",
  },
  {
    id: "r2",
    userName: "Trần Thị B",
    rating: 5,
    comment:
      "Giao hàng nhanh, chất lượng OK. Giá rẻ hơn ngoài tiệm nhiều. 5 sao!",
    images: ["/reviews/review1.jpg"],
    createdAt: "2024-12-10T14:30:00Z",
    likes: 8,
    variant: "Samsung Galaxy S24 Ultra",
  },
  {
    id: "r3",
    userName: "Lê Minh C",
    rating: 5,
    comment: "Mua lần 2 rồi, shop giao nhanh, hàng đẹp. Recommend!",
    createdAt: "2024-12-08T09:15:00Z",
    likes: 5,
  },
  {
    id: "r4",
    userName: "Phạm Hồng D",
    rating: 5,
    comment:
      "Ốp rất đẹp, chất liệu tốt. Chống sốc hiệu quả. Shop tư vấn nhiệt tình.",
    images: ["/reviews/review2.jpg", "/reviews/review3.jpg"],
    createdAt: "2024-12-05T16:45:00Z",
    likes: 15,
    variant: "Đen - iPhone 15",
  },
  {
    id: "r5",
    userName: "Hoàng Anh E",
    rating: 5,
    comment: "Sạc nhanh thật sự, pin lên rất nhanh. Chất lượng xứng đáng với giá tiền.",
    createdAt: "2024-12-01T11:20:00Z",
    likes: 20,
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Kính cường lực iPhone 15 Pro Max full màn hình 9D chống nhìn trộm",
    slug: "kinh-cuong-luc-iphone-15-pro-max-full-man-9d",
    sku: "KC-IP15PM-001",
    price: 45000,
    originalPrice: 120000,
    discount: 63,
    images: [
      "https://placehold.co/800x800/EE4D2D/white?text=Kinh+CL+iPhone15",
      "https://placehold.co/800x800/EE4D2D/white?text=Kinh+CL+2",
      "https://placehold.co/800x800/EE4D2D/white?text=Kinh+CL+3",
    ],
    category: categories[0],
    categoryId: "1",
    description:
      "Kính cường lực iPhone 15 Pro Max full màn hình 9D chống nhìn trộm, chống vân tay, độ cứng 9H. Bảo vệ màn hình tuyệt đối.",
    specifications: {
      "Độ cứng": "9H",
      "Độ dày": "0.33mm",
      "Chất liệu": "Tempered Glass",
      "Tương thích": "iPhone 15 Pro Max",
    },
    variants: [
      {
        id: "v1",
        name: "Loại",
        options: [
          { id: "o1", value: "Thường", stock: 50 },
          { id: "o2", value: "Chống nhìn trộm", price: 55000, stock: 30 },
          { id: "o3", value: "Mờ chống vân tay", price: 50000, stock: 40 },
        ],
      },
    ],
    stock: 120,
    sold: 2847,
    rating: 4.9,
    reviewCount: 1523,
    shopeeRating: 4.9,
    shopeeSold: 2847,
    shopeeReviews: shopeeReviews.slice(0, 3),
    compatibleModels: ["iPhone 15 Pro Max"],
    isFlashSale: true,
    flashSalePrice: 35000,
    flashSaleEnd: "2025-12-31T23:59:59Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-12-20T00:00:00Z",
  },
  {
    id: "2",
    name: "Ốp lưng iPhone 15 Pro Max chống sốc Xundd bảo vệ camera",
    slug: "op-lung-iphone-15-pro-max-chong-soc-xundd",
    sku: "OL-IP15PM-002",
    price: 89000,
    originalPrice: 250000,
    discount: 64,
    images: [
      "https://placehold.co/800x800/222222/white?text=Op+Lung+Xundd",
      "https://placehold.co/800x800/222222/white?text=Op+Lung+2",
    ],
    category: categories[1],
    categoryId: "2",
    description:
      "Ốp lưng chống sốc Xundd cho iPhone 15 Pro Max, viền TPU mềm + lưng PC cứng trong suốt, bảo vệ camera, chống ố vàng.",
    specifications: {
      "Chất liệu": "TPU + PC",
      "Tương thích": "iPhone 15 Pro Max",
      "Tính năng": "Chống sốc, bảo vệ camera",
    },
    variants: [
      {
        id: "v2",
        name: "Màu sắc",
        options: [
          { id: "o4", value: "Trong suốt", stock: 80 },
          { id: "o5", value: "Đen", stock: 60 },
          { id: "o6", value: "Xanh dương", stock: 45 },
        ],
      },
    ],
    stock: 185,
    sold: 5432,
    rating: 4.8,
    reviewCount: 2891,
    shopeeRating: 4.8,
    shopeeSold: 5432,
    shopeeReviews: shopeeReviews.slice(2, 5),
    compatibleModels: ["iPhone 15 Pro Max"],
    isFlashSale: true,
    flashSalePrice: 69000,
    flashSaleEnd: "2025-12-31T23:59:59Z",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-12-18T00:00:00Z",
  },
  {
    id: "3",
    name: "Sạc nhanh 20W PD cho iPhone Type-C chính hãng",
    slug: "sac-nhanh-20w-pd-iphone-type-c",
    sku: "SC-20W-003",
    price: 79000,
    originalPrice: 200000,
    discount: 61,
    images: [
      "https://placehold.co/800x800/FFA500/white?text=Sac+20W+PD",
      "https://placehold.co/800x800/FFA500/white?text=Sac+20W+2",
    ],
    category: categories[2],
    categoryId: "3",
    description:
      "Củ sạc nhanh 20W PD Type-C cho iPhone 15/14/13/12, sạc đầy 50% trong 30 phút. Chip thông minh bảo vệ pin.",
    specifications: {
      "Công suất": "20W",
      "Cổng": "Type-C PD",
      "Input": "100-240V",
      "Output": "5V/3A, 9V/2.22A",
    },
    variants: [],
    stock: 200,
    sold: 8921,
    rating: 4.9,
    reviewCount: 4567,
    shopeeRating: 4.9,
    shopeeSold: 8921,
    shopeeReviews: shopeeReviews,
    compatibleModels: ["iPhone 15", "iPhone 14", "iPhone 13", "Samsung", "Xiaomi"],
    isFlashSale: false,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-12-15T00:00:00Z",
  },
  {
    id: "4",
    name: "Cáp sạc nhanh Type-C to Lightning MFi 1m cho iPhone",
    slug: "cap-sac-nhanh-type-c-lightning-mfi-1m",
    sku: "CAP-CTL-004",
    price: 59000,
    originalPrice: 150000,
    discount: 61,
    images: [
      "https://placehold.co/800x800/4CAF50/white?text=Cap+Type-C",
      "https://placehold.co/800x800/4CAF50/white?text=Cap+2",
    ],
    category: categories[3],
    categoryId: "4",
    description:
      "Cáp sạc nhanh Type-C to Lightning chuẩn MFi Apple, hỗ trợ PD 20W, dây bện nylon siêu bền.",
    specifications: {
      "Chiều dài": "1m",
      "Chuẩn": "MFi Certified",
      "Chất liệu": "Nylon bện",
      "Hỗ trợ": "PD 20W Fast Charging",
    },
    variants: [
      {
        id: "v3",
        name: "Chiều dài",
        options: [
          { id: "o7", value: "1m", stock: 100 },
          { id: "o8", value: "2m", price: 79000, stock: 70 },
        ],
      },
    ],
    stock: 170,
    sold: 3456,
    rating: 4.7,
    reviewCount: 1890,
    shopeeRating: 4.7,
    shopeeSold: 3456,
    shopeeReviews: shopeeReviews.slice(0, 4),
    compatibleModels: ["iPhone 15", "iPhone 14", "iPhone 13", "iPad"],
    isFlashSale: true,
    flashSalePrice: 45000,
    flashSaleEnd: "2025-12-31T23:59:59Z",
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2024-12-12T00:00:00Z",
  },
  {
    id: "5",
    name: "Tai nghe Bluetooth không dây TWS Pro 6 âm thanh HiFi",
    slug: "tai-nghe-bluetooth-tws-pro-6-hifi",
    sku: "TN-TWS6-005",
    price: 69000,
    originalPrice: 350000,
    discount: 80,
    images: [
      "https://placehold.co/800x800/9C27B0/white?text=Tai+Nghe+TWS",
      "https://placehold.co/800x800/9C27B0/white?text=Tai+Nghe+2",
    ],
    category: categories[4],
    categoryId: "5",
    description:
      "Tai nghe Bluetooth TWS Pro 6, âm thanh HiFi, chống ồn, pin 24h, cảm ứng, kết nối ổn định.",
    specifications: {
      "Kết nối": "Bluetooth 5.3",
      "Pin": "Tai nghe 4h, hộp sạc 24h",
      "Chống nước": "IPX5",
      "Driver": "13mm",
    },
    variants: [
      {
        id: "v4",
        name: "Màu",
        options: [
          { id: "o9", value: "Trắng", stock: 90 },
          { id: "o10", value: "Đen", stock: 85 },
        ],
      },
    ],
    stock: 175,
    sold: 12543,
    rating: 4.6,
    reviewCount: 6789,
    shopeeRating: 4.6,
    shopeeSold: 12543,
    shopeeReviews: shopeeReviews,
    compatibleModels: ["Tất cả điện thoại"],
    isFlashSale: true,
    flashSalePrice: 49000,
    flashSaleEnd: "2025-12-31T23:59:59Z",
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2024-12-10T00:00:00Z",
  },
  {
    id: "6",
    name: "Pin sạc dự phòng 10000mAh sạc nhanh 22.5W mini",
    slug: "pin-sac-du-phong-10000mah-22-5w-mini",
    sku: "PDP-10K-006",
    price: 199000,
    originalPrice: 450000,
    discount: 56,
    images: [
      "https://placehold.co/800x800/2196F3/white?text=Pin+Du+Phong",
      "https://placehold.co/800x800/2196F3/white?text=Pin+DP+2",
    ],
    category: categories[5],
    categoryId: "6",
    description:
      "Pin sạc dự phòng 10000mAh, sạc nhanh 22.5W, thiết kế mini nhỏ gọn, hiển thị LED % pin.",
    specifications: {
      "Dung lượng": "10000mAh",
      "Sạc nhanh": "22.5W",
      "Cổng": "Type-C, USB-A",
      "Kích thước": "92x62x25mm",
    },
    variants: [
      {
        id: "v5",
        name: "Màu",
        options: [
          { id: "o11", value: "Trắng", stock: 40 },
          { id: "o12", value: "Đen", stock: 35 },
          { id: "o13", value: "Xanh", stock: 25 },
        ],
      },
    ],
    stock: 100,
    sold: 4321,
    rating: 4.8,
    reviewCount: 2345,
    shopeeRating: 4.8,
    shopeeSold: 4321,
    shopeeReviews: shopeeReviews.slice(1, 4),
    compatibleModels: ["Tất cả điện thoại"],
    isFlashSale: false,
    createdAt: "2024-05-01T00:00:00Z",
    updatedAt: "2024-12-08T00:00:00Z",
  },
  {
    id: "7",
    name: "Giá đỡ điện thoại để bàn hợp kim nhôm xoay 360 độ",
    slug: "gia-do-dien-thoai-de-ban-hop-kim-nhom-360",
    sku: "GD-BAN-007",
    price: 49000,
    originalPrice: 120000,
    discount: 59,
    images: [
      "https://placehold.co/800x800/FF9800/white?text=Gia+Do+DT",
      "https://placehold.co/800x800/FF9800/white?text=Gia+Do+2",
    ],
    category: categories[6],
    categoryId: "7",
    description:
      "Giá đỡ điện thoại để bàn hợp kim nhôm cao cấp, xoay 360 độ, gập gọn, chống trượt.",
    specifications: {
      "Chất liệu": "Hợp kim nhôm",
      "Góc xoay": "360 độ",
      "Tương thích": "4-12.9 inch",
    },
    variants: [
      {
        id: "v6",
        name: "Màu",
        options: [
          { id: "o14", value: "Bạc", stock: 60 },
          { id: "o15", value: "Đen", stock: 55 },
          { id: "o16", value: "Hồng", stock: 30 },
        ],
      },
    ],
    stock: 145,
    sold: 1876,
    rating: 4.7,
    reviewCount: 934,
    shopeeRating: 4.7,
    shopeeSold: 1876,
    shopeeReviews: shopeeReviews.slice(0, 3),
    compatibleModels: ["Tất cả điện thoại", "iPad"],
    isFlashSale: false,
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-12-05T00:00:00Z",
  },
  {
    id: "8",
    name: "Kính cường lực Samsung Galaxy S24 Ultra full keo UV",
    slug: "kinh-cuong-luc-samsung-s24-ultra-keo-uv",
    sku: "KC-SS24U-008",
    price: 89000,
    originalPrice: 250000,
    discount: 64,
    images: [
      "https://placehold.co/800x800/EE4D2D/white?text=Kinh+CL+S24",
      "https://placehold.co/800x800/EE4D2D/white?text=Kinh+CL+S24+2",
    ],
    category: categories[0],
    categoryId: "1",
    description:
      "Kính cường lực Samsung Galaxy S24 Ultra full keo UV, dán bằng tia UV, bám chặt màn hình cong.",
    specifications: {
      "Độ cứng": "9H",
      "Công nghệ": "Full keo UV",
      "Tương thích": "Samsung Galaxy S24 Ultra",
    },
    variants: [],
    stock: 80,
    sold: 1234,
    rating: 4.8,
    reviewCount: 678,
    shopeeRating: 4.8,
    shopeeSold: 1234,
    shopeeReviews: shopeeReviews.slice(1, 4),
    compatibleModels: ["Samsung Galaxy S24 Ultra"],
    isFlashSale: false,
    createdAt: "2024-07-01T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
];

export const banners: Banner[] = [
  {
    id: "b1",
    image: "https://placehold.co/1200x400/EE4D2D/white?text=FLASH+SALE+50%25+PHU+KIEN+DIEN+THOAI",
    mobileImage: "https://placehold.co/600x300/EE4D2D/white?text=FLASH+SALE+50%25",
    link: "/products?sale=true",
    title: "Flash Sale 50%",
    order: 1,
  },
  {
    id: "b2",
    image: "https://placehold.co/1200x400/FF6B35/white?text=OP+LUNG+CHINH+HANG+GIA+SOC",
    mobileImage: "https://placehold.co/600x300/FF6B35/white?text=OP+LUNG+GIA+SOC",
    link: "/products?category=op-lung",
    title: "Ốp lưng chính hãng",
    order: 2,
  },
  {
    id: "b3",
    image: "https://placehold.co/1200x400/D73211/white?text=SAC+NHANH+20W+FREE+SHIP",
    mobileImage: "https://placehold.co/600x300/D73211/white?text=SAC+NHANH+FREE+SHIP",
    link: "/products?category=sac-adapter",
    title: "Sạc nhanh Free Ship",
    order: 3,
  },
];

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("vi-VN").format(price) + "₫";
}

export function formatSold(sold: number): string {
  if (sold >= 1000) {
    return (sold / 1000).toFixed(1) + "k";
  }
  return sold.toString();
}
